### ISSUE TITLE
Handling of FFT-Normalizations in pyfar

### ISSUE THREAD

**Issue by f-brinkmann** [pyfar/pyfar#262]
## General

* pyfar version: all

## Description

FFT normalization is implemented in `pyfar.fft.normalization` and `Signal.freq` always returns the normalized spectrum (probably inspired by the ITA-Toolbox for Matlab). During coding pyfar, we came across a couple of places where this might not be the best solution, and where we have to

- remove the normalization,
- do some processing, and
- add the normalization again.

This is not only additional code, but also makes coding pyfar prone to errors. So far, the only place, where we directly used the normalized spectrum were the plot functions. This made me think of two questions

1. Do we want to change the current handling?
2. If yes, do we want to break backwards compatibility and move to pyfar 1.0?

**If the answer to 1. is yes, I would propose the following**
Add a property and setter to `Signal`, e.g., `Signal.freq_raw`. Internally we would only store the raw, i.e., not normalized frequency data. The old property `Signal.freq` would return the normalized data. The old setter `Signal.freq` would apply the inverse normalization to the input data and save it.

**If the answer to 2. is yes, I would propose the following**
The property `Signal.freq` returns the non-normalized data. This seems to be the most common case and more intuitive - at least for me. We add a property, e.g., `Signal.freq_norm` that behaves as `Signal.freq` described in the previous paragraph.

**Third option**
Add `freq_raw` and `freq_norm` and keep `freq` for two minor versions with a deprecation warning. In this case `freq_norm` would only have a getter, and return real values spectra in some cases.

What are your thoughts on this?

**Comment by f-brinkmann** [comment]
Discussed in the weekly
- we want the third option
- we will discuss the option of a setter/converter for `freq_norm` separately

**Comment by sikersten** [comment]
In fact, the current `signal.freq` setter sets the normalized spectrum (see `test_setter_freq()`). We have two options here:

1. Break backwards compatibility by either removing the setter (and later replace it by functions to set `freq_norm`) or by changing it to set `freq_raw`.
2. Keep the functionality to set the normalized spectrum. We should then address the problems of setting a normalized spectrum within this implementation (especially for the `'power'` and `'psd'` norms).

What's your opinion?

**Comment by f-brinkmann** [comment]
I would suggest to leave `signal.freq` as it is but raise a deprecation warning that it will be removed in 0.6.0. I'm not sure what the final vote was for the normalized spectra that do not have phase information. I think we wanted to leave that as it is, i.e., including the phase information.

**Comment by sikersten** [comment]
Currently, `freq` is inherited by the `Signal `class from `FrequencyData` and it corresponds to `freq_norm`. The problem is, that in a strict definition `FrequencyData.freq` neither corresponds to `Signal.freq_raw` (the unnormalized FFT spectrum of a time signal) as there is no time signal, nor to `Signal.freq_norm` (e.g., due to dependency on the sampling rate of the `'psd'` normalization). So, a conversion from a generic `FrequencyData `object to a `Signal `object would require additional information.
To keep backwards compatibility, it makes sense to keep `Signal.freq` as equivalent to `freq_norm` until 0.6.0.
But I'm not sure what to afterwards. Ideally, we would remove `freq` from the Signal class to only have two well defined spectrum properties `freq_raw` and `freq_norm`, but `freq` is inherited from FrequencyData. So would it make sense to remove the inheritance?

**Comment by f-brinkmann** [comment]
+1 for keeping `Signal.freq` until 0.6.0 and introducing `freq_raw` and `freq_norm`

If it seems unelegant to you to keep the inheritance I am fine with removing it. I also think that it might make the differences between the concepts and the code of the classes more clear.

**Comment by sikersten** [comment]
As discussed in the weekly, we will continue with keeping `Signal.freq` as property containing the normalized spectrum and add `freq_raw` as attribute containing the unnormalized spectrum. This will ensure backwards compatibility and tests do not need to be touched.
