### ISSUE TITLE
Coordinate set and get inconsistant

### ISSUE THREAD

**Issue by ahms5** [pyfar/pyfar#353]
## Description

inconsistant behavior with setting and getting coordinates. For the setter you get an array x 3 and for the setter you have to set each individual. See below

## What I Did

```
    sph = coords.get_sph()
    sph[:, :, 2] = 2
    # coords.set_sph(sph) # Does not work, would be more consistant
    coords.set_sph(sph[..., 0], sph[..., 1], sph[..., 2])
```

**Comment by f-brinkmann** [comment]
I forgot the reason why we designed it that way. We could make that possible by checking if the first input satisfies `sph.shape[-1]==3` if the other two inputs are not provided.

**Comment by f-brinkmann** [comment]
We decided the following
- have setter and getter for each coordinate, e.g., `x` and `azimuth`, and deprecate the current setter and getter two minor releases later.
- We will use the converters that we already have, instead of adding new converters for each coordinate.
- Internally, the data will always be saved in Cartesian coordinates.
- We think about discarding numerical inaccuracies by discard one bit above LSB
- Check range restrictions for circular coordinates, e.g., azimuth, and maybe relax them.

**Comment by ahms5** [comment]
polar coordinates seems to be defined from (-pi to pi], but according to the doc its from 0 to 2*pi (Coordinates Concept). Which should be right?

**Comment by f-brinkmann** [comment]
> polar coordinates seems to be defined from (-pi to pi], but according to the doc its from 0 to 2*pi (Coordinates Concept). Which should be right?

What coordinate (e.g., azimuth, colatitude, etc.) are you refering to and where is the conflicting information listed?

**Comment by ahms5** [comment]
> 

It is the polar angle from sph side system, according to the figure in Concept Coordinates
`| sph, side          | lateral  | polar      | radius   | rad, deg |`

**Comment by f-brinkmann** [comment]
I think everything is correct there. polar angle=0 is a frontal source, pi/2 a source above, pi to the back 3 pi/2, below and 2 pi is front again. It's the lateral angle that goes from -pi tp pi. Is there a way that the figure could be improved?
