### ISSUE TITLE
find_nearest_sph only works if all points have the same radius

### ISSUE THREAD

**Issue by SDX-LV** [pyfar/pyfar#395]
## General

* pyfar version: latest
* Did you install pyfar via pip: yes

## Description
Hi,

In https://github.com/pyfar/pyfar/blob/main/pyfar/classes/coordinates.py on line 927 the check is hard-coded to `if delta_radius > 1e-15:` and therefore even if I change `atol` value in https://pyfar.readthedocs.io/en/latest/classes/pyfar.coordinates.html#pyfar.classes.coordinates.Coordinates.find_nearest_sph  the method never works on for example a normal Mesh2HRTF SOFA data.

## What I Did

```
SOFA_signals, SOFA_sources, SOFA_receivers = pf.io.read_sofa([ Mesh2HRTF HRIR from Default evaluation grid], verify=False)


Radiuses = SOFA_sources._points[:, 2]  # info on all source distances
set(Radiuses)  # notice the tolerance

distance = Radiuses.min()   # normally  unique_Radiuses.min()
hitA_ind, hitA_mask = SOFA_sources.find_nearest_sph(30, 0, distance, 5, domain='sph', convention='top_elev', unit='deg', show=Debug_plot_Selections, atol=0.04)

```

## Labels

**bug:**

 **coordinates**

**Comment by f-brinkmann** [comment]
Its intended to work only if the points have the same radius, but the tolerance might be a bit to tight. What tolerance would be required in this case?

**Comment by SDX-LV** [comment]
In this case `set(Radiuses)` gives `{1.5, 1.4999999999999998, 1.5000000000000002}`
I wanted to use 0.04m - basically some radius +/- 4cm. Maybe in some ultra-nearfield case someone is interested in more distance resolution, but for typical auralization SOFA datasets most likely no one has finer step from one radius to another than 10cm.

**Comment by f-brinkmann** [comment]
To be more clear. `find_nearest_sph` searches by great circle distance, that's why it expects points to have the same radius. `atol` does not effect the radius but the tolerance for the great circle distance. We can discuss to add a tolerance parameter for the radius as well in case someone wants to search across different radii. In your case the difference between radii is 4.4e-16. So in any case the default tolerance might be a little tight.

**Comment by SDX-LV** [comment]
Note that my case is the result of https://github.com/Any2HRTF/Mesh2HRTF/tree/develop/mesh2hrtf/Mesh2Input/EvaluationGrids/Data/Default
evaluation grid. So I guess the tolerance could be relaxed.

**Comment by f-brinkmann** [comment]
We discussed that we want to have an additional parameter `range=None`. by default, the nearest points are searched for all radii, and range can be used to restrict the radius.

**Comment by f-brinkmann** [comment]
During refactoring we noted that the restriction is due to using `scipy.spatial.cKDTree` for the search, which uses cartesian coordinates to find the nearest points. This means that a search ignoring the radius would mean a complete refactor of `Coordinates.search_within`. If someone wants to take the effort, we could discuss possible solutions. But we removed it from our short term to-do list at least for now.
