### ISSUE TITLE
Support for infinite radius in the SourcePosition

### ISSUE THREAD

**Issue by stealthBanana** [pyfar/pyfar#625]
## General

* pyfar version: 0.6.5
* sofar version: 1.1.3
* Python version: 3.10.12
* Operating System: Ubuntu 22.04
* Did you install pyfar via pip: No poetry 1.8.2

## Description

When reading a SOFA containing coordinates with inifinite radius with pyfar some coordinates are wrong and others become nan.

## What I Did

```
import sofar as sf
import pyfar as pf

sofa = sf.Sofa('SimpleFreeFieldHRTF')

sofa.SourcePosition_Type = "spherical"
sofa.SourcePosition_Units = "degree, degree, metre"
sofa.SourcePosition = [
    [180,    0,     float('inf')],
    [90,     0.1,   float('inf')],
    [45,     -0.1,  float('inf')],
    [0,      10,    float('inf')],
]

sofa.ReceiverPosition = [[0, 0, 0]]
sofa.ReceiverPosition_Type = "cartesian"
sofa.ReceiverPosition_Units = "metre"

sofa.Data_Real = [[5], [5], [5], [5]]
sofa.Data_Imag = [[0], [0], [0], [0]]
sofa.N = [1500]

sofa.verify(issue_handling="raise", mode="write")
sf.write_sofa('tmp.sofa', sofa)

signal, sources, receiver = pf.io.read_sofa('tmp.sofa')
print(sources.azimuth*180/np.pi)
print(sources.elevation*180/np.pi)
print(sources.radius)
```

## The output
```
[135.  45.  45.  nan]
[nan nan nan nan]
[inf inf inf nan]
```

**Comment by f-brinkmann** [comment]
Thanks for reporting. I think this happens because we create a coordinate object when reading sofa files into pyfar and always store cartesian coordinates inside the object. The error probably happens when converting from spherical to cartesian coordinates. However, I would argue that writing `inf` to a sofa file is invalid because sofa always expects full coordinates (please correct me if you think I'm wrong here). However the error is not detected by sofar and pyfar. I will mark this for discussion during our next weekly.

Why are you writing `inf` values? I would assume this might be an option when having simulated HRTFs with plane waves, but maybe adding a large radius and a comment to the sofa file would be an alternative option.

**Comment by stealthBanana** [comment]
Yes, we do use the same incidence angle for both ears therefore, assunming that the distance of the source is `inf`. I will opt for a large value.

Thanks
